### ISSUE TITLE
Support debugging

### ISSUE THREAD

**Issue by koutheir** [LucasBullen/redOx#12]
Please add support for debugging.

**Comment by LucasBullen** [comment]
Implemented with 9317bcc. If any issues or additions are requested then feel free to open issues or submit PRs.

**Comment by koutheir** [comment]
@LucasBullen:
I still cannot create a Debug configuration to start the executable in debug mode. The only thing I can add to the project is a Run configuration to simply execute the program. This issue is still open.

**Comment by LucasBullen** [comment]
True, I'll keep this issue open until the install sites are updated. Features only available from master.

**Comment by koutheir** [comment]
Thank you. If you want beta testers to use the master tree to run the plugin, then please provide some building/hacking instructions in how to do so. Beta testers can bear the additional burden of building from the master directly instead of using the Eclipse update site, if they know how to do so.

**Comment by LucasBullen** [comment]
Instruction for installing: https://github.com/LucasBullen/redOx/blob/master/documentation/Installation.md
Debug is available through all sources
