### ISSUE TITLE
Syntax highlighting issue

### ISSUE THREAD

**Issue by koutheir** [LucasBullen/redOx#14]
Syntax highlighting of a valid Rust code is incorrectly done. Here is a sample:
```
fn main() {
    println!("Hello, world!");
}

lazy_static!{
pub static ref bar : Vec<&'static str> =
    vec!["a", "b", "c", "d", "e"];

pub static ref t: i32 = 0;
}

fn foo() {
}
```

Here is the incorrect syntax highlighting performed by redOx:
![screenshot_20180105_155115](https://user-images.githubusercontent.com/1145849/34614194-ec5686ac-f230-11e7-90e4-746334c514ca.png)

Here is the correct syntax highlighting performed by RustDT:
![screenshot_20180105_155104](https://user-images.githubusercontent.com/1145849/34614209-f88981f4-f230-11e7-94c6-6221776ca40b.png)

**Comment by LucasBullen** [comment]
Fixed and implemented with 4da697c. Good find!
