### ISSUE TITLE
No autocomplete for macro

### ISSUE THREAD

**Issue by akurtakov** [LucasBullen/redOx#18]
Open any rust file. Try to autocomplete any macro like println or write just to find they are not in the list at all.

**Comment by LucasBullen** [comment]
Turns out rls in fact does not support macros, vscode gets around this by including some including println as snippets: https://github.com/rust-lang-nursery/rls-vscode/commit/81aece7ef38641eb9176a567e1e40d8611bb1689 Will look into doing the same.

**Comment by LucasBullen** [comment]
Snippet capabilities added in 0c68cee
