### ISSUE TITLE
Provide format based on rustfmt

### ISSUE THREAD

**Issue by akurtakov** [LucasBullen/redOx#19]
1. Make sure that rustup installs rustfmt component
2. Provide Save action to call it on the given file
3. Provide a comand for manually calling it

See https://github.com/rust-lang-nursery/rustfmt for details about it.

**Comment by LucasBullen** [comment]
Issue resolved for Photon with e97d453. Will keep issue open while fixing for Oxygen (Requires packaging lsp4e 0.6.0 with Oxygen manually)

**Comment by akurtakov** [comment]
Don't spend too much time on it. As it's new plugin it's fine to require Oxygen if lsp4e is not a simple rebuild.

**Comment by LucasBullen** [comment]
Format is now enabled with ff73ef8.
