### ISSUE TITLE
Issue with rustup installation

### ISSUE THREAD

**Issue by akurtakov** [LucasBullen/redOx#20]
If a toolchain is missing (e.g. beta) and one clicks Apply and right after that(fast enough so download hasn't completed) Apply and Close button there is error printed. Depending on what was already downloaded one can get error messages like toolchain can not be installed, toolchain doesn't contain RLS and probably others.
A check whether installation of the given toolchain is ongoing should be done and second installation of the same toolchain should not be started.

**Comment by LucasBullen** [comment]
Fixed with e171cf6
