### ISSUE TITLE
Error markers not cleaned up properly

### ISSUE THREAD

**Issue by akurtakov** [LucasBullen/redOx#21]
Play with code in order to have many errors . Fix them. Editor leaves some error markers not cleaned.
![screenshot from 2018-01-10 11-53-44](https://user-images.githubusercontent.com/574788/34766443-1f86157c-f5fd-11e7-9fc4-97d6e8594019.png)

**Comment by LucasBullen** [comment]
Bringing up issue with the RLS: https://github.com/rust-lang-nursery/rls/issues/652

**Comment by LucasBullen** [comment]
Issue resolved with nightly release of RLS.
