### ISSUE TITLE
No autocomplete for function, No code format , No build

### ISSUE THREAD

**Issue by di3663** [LucasBullen/redOx#22]
No autocomplete for function, No code format , No build

When create cargo project, alert " Cargo command not found. Fix path in the Rust Preferences Page.", but do set cargo path (rust stable 32bit on windows).

**Comment by LucasBullen** [comment]
@di3663 could you see if this new patch fixes your issues?

**Comment by di3663** [comment]
No, still not, 

I unchecked 'Use default paths' and input a windows-style path ('D:\TOOL\Z\.rustup\toolchains\stable-i686-pc-windows-msvc\bin\cargo.exe').

But reopen the preferences page again will found the option still checked and path reseted. By the way, the default path is '/d/TOOL/Z/.rustup/toolchains/stable-i686-pc-windows-msvc/bin/cargo'

And I found another bug (maybe), namespace autocomplete not work in 4.7.
 4.8 seems works at last try. Well, maybe I should keep using rustdt.

**Comment by LucasBullen** [comment]
Thanks for the feedback on the default path, think that gives me the hint I need to fix it.

Currently, the download sites are not being updated with all the fixes as they have to be packaged from master which might explain the namespace autocompletion.

Understandable to stick with RustDT for the time being, once debug is added to redOx and all these beginning issues are resolved I'll ping you again if you wish to give it another more successful go.
