### ISSUE TITLE
Add a Cargo.toml Editor

### ISSUE THREAD

**Issue by LucasBullen** [LucasBullen/redOx#7]
Add support to the Generic Editor for Cargo.toml files: http://doc.crates.io/manifest.html

**Comment by LucasBullen** [comment]
Implemented with dcb4281. Will be reopened if requested for more edition support (ex. completion assist)

**Comment by norru** [comment]
Only works for `Cargo.toml`, not working for `*.toml`

**Comment by mickaelistria** [comment]
@norru Please open a new ticket to generalize to *.toml.

**Comment by norru** [comment]
https://github.com/eclipse/corrosion/issues/167
